MinimumStatiqWebVersion-CleanBlog: "1.0.0-beta.33"
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return siteTitle == title ? siteTitle : string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{title} - {siteTitle}");
  }
Copyright: => $"Copyright © {DateTime.Now.Year}"
PostSources: '**/*'
IsPost: => Outputs.FilterSources(Context.GetString("PostSources")).ContainsById(Document)
Layout: /_layout.cshtml